TRUNCATE TABLE geoname;
TRUNCATE TABLE alternatename;
TRUNCATE TABLE countryinfo;
TRUNCATE TABLE iso_languagecodes;
TRUNCATE TABLE admin1Codes;
TRUNCATE TABLE admin1CodesAscii;
TRUNCATE TABLE featureCodes;
TRUNCATE TABLE timeZones;
TRUNCATE TABLE continentCodes;
